spring.datasource.url=jdbc:postgresql://localhost:5432/user_service_test
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

logging.level.org.klimtsov=DEBUG
logging.level.org.springframework.web=INFO

#health endpoint
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

spring.jpa.open-in-view=false

#Kafka Configuration.
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#?????????????? ???????? ???????.
spring.kafka.admin.properties.auto.create.topics.enable=false

#???????? ? ?????????.
spring.kafka.producer.acks=1
spring.kafka.producer.retries=3
spring.kafka.producer.batch-size=16384
spring.kafka.producer.buffer-memory=33554432
spring.kafka.producer.properties.max.block.ms=5000
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.properties.delivery.timeout.ms=120000

#??????????? Kafka.
logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=INFO